required = ["github.com/onsi/ginkgo/ginkgo"]

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true
