#!/bin/sh

set -eu -o pipefail

jq -n '
  {
    "source": {
      "uri": "file://\(env.PWD)",
      "dev_releases": true
    }
  }
' \
| /opt/resource/check \
| jq '
  {
    "source": {
      "uri": "file://\(env.PWD)",
      "dev_releases": true
    },
    "version": first
  }
' \
| /opt/resource/in "$( realpath "$1" )" \
> /dev/null
