---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-release-resource
inputs:
- name: repo
outputs:
- name: release
run:
  dir: repo
  path: create-dev-release
  args:
  - ../release
